services:
  svelte-app:
    build: .
    container_name: acutest_app
    restart: always
    ports:
      - "3000:3000"
    environment:
      # SvelteKit needs to know where it's hosted to prevent CSRF errors
      - ORIGIN=http://localhost:3000
      - PORT=3000
      # If you have API keys, add them here
      # - PUBLIC_API_URL=...

